---
# tasks file for roles/osp-instance-delete
  #- name: Fetch Instance Info
  - name: Fetch openstack Instance Info
    os_server_info:
      cloud: openstack
      region_name: regionOne
    register: r_os_server_info

  - name: debug task Fetch Instance Info
    debug:
      var: item.id
      verbosity: 1
    loop: "{{ r_os_server_info.openstack_servers }}"

  - name: Delete instances
    os_server:
       name: "{{ item.id }}"
       delete_fip: true
       state: absent
    loop: "{{ r_os_server_info.openstack_servers }}"
   
