- import_playbook: venv.yml

- name: create OSP instances
  hosts: localhost
  connection: local
  become: no
  gather_facts: true
  #vars:
  #  ansible_python_interpreter: /tmp/openstack-venv/bin/python
  roles:
   - osp-servers
   - osp-facts
