- hosts: localhost
  gather_facts: true
  roles:
  - name: osp-facts

  tasks: 

  - debug:
      var: hostvars
      verbosity: 1

  - name: Check hosts are reachable over SSH
    wait_for:
      host: "{{ item }}"
      port: 22
      search_regex: OpenSSH
      timeout: 20
    loop: "{{ groups['QA'] }}"
    #loop: "{{ lookup( 'dict', hostvars ) }}"
    #loop: "{{ groups['appdbs'] + groups['apps'] + groups['frontends'] }}"

  - name: Curl website
    vars: 
      frontend_host: "{{ groups['frontends'][0] }}"
      url: "{{ hostvars[frontend_host]['ansible_host'] }}/"
    shell: "/usr/bin/curl {{ frontend_host }}"
    #shell: "/usr/bin/curl {{ url }}"
    register: r_webpage

  - name: debug curl 
    debug: 
      var: r_webpage
      verbosity: 1

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible' not in r_webpage.stdout"
    tags:
      - osp.smoke
    
