---
- hosts: localhost
  become: yes
  gather_facts: yes
  roles:
    - osp-facts

  tasks:

   - debug: 
       var:  hostvars[item]
       #var:  hostvars[item]['ansible_facts']['location']
     loop: "{{ groups['apps']  }}"

   - name: Generate static inventory file
     template:
       src: inventory.j2
       dest: "/tmp/inventory"
     delegate_to: localhost

