
#- name: load_balancers - add repo
#  copy:
#    src: files/open_three-tier-app.repo
#    dest: /etc/yum.repos.d/open_three-tier-app.repo

- name: Install load balancer packages
  package:
    name: "{{ load_balancer_packages }}"
    state: present

- name: Configure haproxy load balancing
  template:
    src: templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart_haproxy

- name: Enable Haproxy
  service:
    name: haproxy
    state: started
    enabled: true

